org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.18.4
loom_version=1.17.13
fabric_api_version=0.116.14+1.21.1
fabric_kotlin_version=1.13.13+kotlin.2.4.10
cobblemon_version_id=S1TrAn8c
geckolib_version=4.9.2

mod_version=0.4.0-alpha.69
maven_group=com.emipokemon
archives_base_name=emipokemon
